// BSD match details for events synced by provider `bsd`.
// `kind=lineup` caches a complete confirmed XI+bench; `kind=live` caches the
// score/status and full incidents timeline in the same shapes used by the
// mobile app's existing lineup/live cards.

import { createClient } from 'jsr:@supabase/supabase-js@2';
const CORS={ 'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS' };
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:CORS});
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('invalid_response');return value as Record<string,unknown>}
function text(value:unknown){return typeof value==='string'&&value.trim()?value:null}
function number(value:unknown){if(typeof value==='number'&&Number.isFinite(value))return value;if(typeof value==='string'&&value!==''&&Number.isFinite(Number(value)))return Number(value);return null}
async function hasUser(supabase:ReturnType<typeof createClient>,request:Request){const jwt=(request.headers.get('Authorization')??'').replace(/^Bearer\s+/i,'').trim();return jwt?((await supabase.auth.getUser(jwt)).data.user!==null):false}
async function api(path:string,key:string){const response=await fetch(`https://sports.bzzoiro.com/api/v2${path}`,{headers:{Authorization:`Token ${key}`},signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(`http_${response.status}`);return response.json()}
function gridRows(formation:string|null){const parts=(formation??'').split('-').map(Number).filter(Number.isFinite);return parts.length?[1,...parts]:[1,4,4,2]}
function photo(value:Record<string,unknown>){const id=number(value.id);if(id!==null)return `https://sports.bzzoiro.com/img/player/${id}/?sor=true&bg=transparent`;return text(value.playerImage??value.player_image)}
function players(side:Record<string,unknown>){const formation=text(side.formation);const starters=Array.isArray(side.players)?side.players:[];const subs=Array.isArray(side.substitutes)?side.substitutes:[];const counts=gridRows(formation);let index=0;const normalized=starters.map(value=>{const p=object(value);while(index>=counts.slice(0,-1).reduce((a,b)=>a+b,0)&&counts.length>1)break;let consumed=0,row=1,col=1;for(let r=0;r<counts.length;r++){if(index<consumed+counts[r]){row=r+1;col=index-consumed+1;break}consumed+=counts[r]}index++;return{id:String(p.id??p.name),name:String(p.name??''),number:number(p.jersey_number),position:text(p.position),isSubstitute:false,photoUrl:photo(p),isCaptain:Boolean(p.captain),countryCode:null,grid:{row,col}}});
  for(const value of subs){const p=object(value);normalized.push({id:String(p.id??p.name),name:String(p.name??''),number:number(p.jersey_number),position:text(p.position),isSubstitute:true,photoUrl:photo(p),isCaptain:Boolean(p.captain),countryCode:null,grid:null})}
  return{players:normalized,starters:starters.length,formation};
}
function incident(value:unknown){const i=object(value),type=String(i.type??'other');let normalized='other',player=text(i.player),assist:null|string=null,detail=type;
  if(type==='goal'){normalized='goal';detail=text(i.goal_type)??'Normal Goal';assist=text(i.assist)}
  else if(type==='card'){normalized='card';detail=`${text(i.card_type)??'Card'}${text(i.reason)?` · ${text(i.reason)}`:''}`}
  else if(type==='substitution'){normalized='substitution';player=text(i.player_in);assist=text(i.player_out);detail='Substitution'}
  else if(type.toLowerCase().includes('var')){normalized='var';detail=text(i.decision)??'VAR'}
  return{minute:number(i.minute)??0,extraMinute:number(i.added_time),type:normalized,detail,isHome:Boolean(i.is_home),player,assistOrSubIn:assist};
}
function statusShort(status:string,period:string|null){if(status==='finished')return'FT';if(status==='postponed')return'PST';if(status==='cancelled')return'CANC';if(period==='HT')return'HT';if(status==='live')return'2H';return'NS'}
const STAT_KEYS=['ball_possession','expected_goals','expected_goals_on_target','total_shots','shots_on_target','big_chances','corner_kicks','fouls','passes','pass_accuracy_pct','offsides','yellow_cards','red_cards','goalkeeper_saves'];
function statRows(stats:Record<string,unknown>){const home=object(stats.home),away=object(stats.away);return STAT_KEYS.map(key=>({key,home:number(home[key]),away:number(away[key])})).filter(r=>r.home!==null||r.away!==null)}
Deno.serve(async request=>{if(request.method==='OPTIONS')return new Response('ok',{headers:CORS});let eventId:string|null=null,kind:string|null=null;try{const body=await request.json();if(typeof body.eventId==='string')eventId=body.eventId;if(typeof body.kind==='string')kind=body.kind}catch{}if(!eventId||!['lineup','live','stats'].includes(kind??''))return json({error:'eventId and kind required'},400);
  const supabase=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);if(!(await hasUser(supabase,request)))return json({error:'unauthorized'},401);const{data,error}=await supabase.from('events').select('external_ids,lineup_cache,lineup_cached_at,live_cache,live_cached_at').eq('id',eventId).maybeSingle();if(error)return json({error:error.message},500);if(!data)return json({error:'event not found'},404);const bsdId=data.external_ids?.bsd;if(!bsdId)return json({available:false,reason:'not_bsd'});const key=Deno.env.get('API_BSD_FOOTBALL_KEY');if(!key)return json({available:false,reason:'not_configured'});
  try{if(kind==='lineup'){const body=await api(`/events/${bsdId}/lineups/`,key);if(body.lineup_status!=='confirmed'||!body.lineups?.home||!body.lineups?.away)return json({available:false,lineup:null,reason:'not_confirmed'});const home=players(object(body.lineups.home)),away=players(object(body.lineups.away));if(home.starters<11||away.starters<11)return json({available:false,lineup:null,reason:'partial'});const lineup={home:home.players,away:away.players,homeFormation:home.formation,awayFormation:away.formation};await supabase.from('events').update({lineup_cache:lineup,lineup_cached_at:new Date().toISOString()}).eq('id',eventId);return json({available:true,lineup})}
    if(kind==='stats'){const[statsBody,playerBody]=await Promise.all([api(`/events/${bsdId}/stats/`,key),api(`/events/${bsdId}/player-stats/`,key)]);const ratings:Record<string,{rating:number;minutes:number|null}>={};for(const value of Array.isArray(playerBody.player_stats)?playerBody.player_stats:[]){const p=object(value);const rating=number(p.rating);if(rating===null||p.player_id===undefined)continue;ratings[String(p.player_id)]={rating,minutes:number(p.minutes_played)}}const rows=statsBody.stats?statRows(object(statsBody.stats)):[];if(!rows.length)return json({available:false,stats:null,reason:'no_stats'});return json({available:true,stats:{rows,ratings}})}
    const[detail,incidents]=await Promise.all([api(`/events/${bsdId}/`,key),api(`/events/${bsdId}/incidents/`,key)]);const state={fixtureId:Number(bsdId),status:statusShort(String(detail.status??''),text(detail.period)),elapsed:number(detail.current_minute),homeScore:number(detail.home_score),awayScore:number(detail.away_score),events:(Array.isArray(incidents.incidents)?incidents.incidents:[]).filter((value:unknown)=>String(object(value).type??'')!=='period').map(incident)};await supabase.from('events').update({live_cache:state,live_cached_at:new Date().toISOString()}).eq('id',eventId);return json({available:true,state})
  }catch(caught){return json({available:false,reason:caught instanceof Error?caught.message:'unknown'})}
});
